var DecisionTree = require('decision-tree');

module.exports={
 training_data : [
{'material':'Metal','weight':3,'shape':'Round','color':'Brown','quality':'New','size':1,'temperature':2,'behavior':'Disarm'},
{'material':'Metal','weight':3,'shape':'Square','color':'Black','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
{'material':'Metal','weight':4,'shape':'Round','color':'Black','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Metal','weight':4,'shape':'Round','color':'Brown','quality':'Old','size':4,'temperature':3,'behavior':'Secure'},
{'material':'Metal','weight':4,'shape':'Square','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Metal','weight':4,'shape':'Square','color':'Black','quality':'Normal','size':3,'temperature':2,'behavior':'Detonate'},
{'material':'Metal','weight':5,'shape':'Elipse','color':'Green','quality':'Normal','size':3,'temperature':1,'behavior':'Disarm'},
{'material':'Metal','weight':5,'shape':'Square','color':'Grey','quality':'Old','size':1,'temperature':4,'behavior':'Secure'},
{'material':'Metal','weight':5,'shape':'Round','color':'Grey','quality':'Old','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Metal','weight':5,'shape':'Round','color':'Black','quality':'Normal','size':2,'temperature':3,'behavior':'Disarm'},
{'material':'Metal','weight':6,'shape':'Non-regular','color':'Colorful','quality':'New','size':2,'temperature':4,'behavior':'Secure'},
{'material':'Metal','weight':6,'shape':'Round','color':'Grey','quality':'Old','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Metal','weight':5,'shape':'Round','color':'Grey','quality':'Old','size':4,'temperature':3,'behavior':'Secure'},
{'material':'Metal', 'weight': 1, 'shape':'Non-regular', 'color': 'Colorful', 'quality': 'Old','size':1,'temperature':2, 'behavior': 'Detonate' },
{'material':'Metal', 'weight': 4,'shape':'Elipse','color':'Gold','quality':'Normal','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Metal', 'weight': 4,'shape':'Square','color':'Gold','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Metal', 'weight': 3,'shape':'Round','color':'Brown','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
{'material':'Metal', 'weight': 6,'shape':'Round','color':'Grey','quality':'Normal','size':4,'temperature':3,'behavior':'Secure'},
{'material':'Metal', 'weight': 5,'shape':'Elipse','color':'Grey','quality':'Old','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Metal', 'weight': 2,'shape':'Square','color':'Brown','quality':'New','size':2,'temperature':3,'behavior':'Detonate'},
{'material':'Metal', 'weight': 2,'shape':'Elipse','color':'Brown','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Metal', 'weight': 3,'shape':'Non-regular','color':'Black','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Metal', 'weight': 4,'shape':'Round','color':'Colorful','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Metal', 'weight': 5,'shape':'Square','color':'Gold','quality':'New','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Metal', 'weight': 6,'shape':'Round','color':'Brown','quality':'Normal','size':2,'temperature':3,'behavior':'Secure'},
{'material':'Metal', 'weight': 2,'shape':'Elipse','color':'Grey','quality':'New','size':1,'temperature':2,'behavior':'Detonate'},
{'material':'Metal', 'weight': 3,'shape':'Non-regular','color':'Black','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Metal', 'weight': 2,'shape':'Round','color':'Green','quality':'Normal','size':3,'temperature':2,'behavior':'Detonate'},
{'material':'Metal', 'weight': 3,'shape':'Elipse','color':'Green','quality':'New','size':4,'temperature':1,'behavior':'Disarm'},
{'material':'Metal', 'weight': 4,'shape':'Square','color':'Black','quality':'Normal','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Metal', 'weight': 5,'shape':'Round','color':'Brown','quality':'New','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Metal', 'weight': 3,'shape':'Non-regular','color':'Black','quality':'Old','size':1,'temperature':2,'behavior':'Detonate'},
{'material':'Metal', 'weight': 4,'shape':'Elipse','color':'Brown','quality':'Old','size':2,'temperature':4,'behavior':'Secure'},
{'material':'Metal', 'weight': 1,'shape':'Non-regular','color':'Colorful','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},

{'material':'Aluminum','weight':2,'shape':'Elipse','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Aluminum','weight':2,'shape':'Elipse','color':'Grey','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum','weight':2,'shape':'Round','color':'Colorful','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
{'material':'Aluminum','weight':2,'shape':'Round','color':'Green','quality':'New','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Green','quality':'Old','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Grey','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum','weight':4,'shape':'Round','color':'Brown','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Black','quality':'Old','size':1,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum','weight':4,'shape':'Round','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum','weight':4,'shape':'Round','color':'Brown','quality':'Old','size':2,'temperature':4,'behavior':'Secure'},
{'material':'Aluminum','weight':5,'shape':'Round','color':'Grey','quality':'Normal','size':4,'temperature':2,'behavior':'Detonate'},
{'material':'Aluminum','weight':5,'shape':'Round','color':'Black','quality':'Old','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Aluminum','weight':5,'shape':'Non-regular','color':'Brown','quality':'Old','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Aluminum','weight':6,'shape':'Round','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum','weight':6,'shape':'Round','color':'Brown','quality':'Old','size':4,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum','weight':6,'shape':'Elipse','color':'Grey','quality':'Normal','size':1,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum', 'weight':1 ,'shape':'Elipse','color':'Colorful','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':2 ,'shape':'Non-regular','color':'Green','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':2 ,'shape':'Elipse','color':'Black','quality':'Old','size':1,'temperature':2,'behavior':'Detonate'},
{'material':'Aluminum', 'weight':3 ,'shape':'Square','color':'Gold','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':3 ,'shape':'Round','color':'Brown','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':4 ,'shape':'Round','color':'Black','quality':'Old','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Aluminum', 'weight':4 ,'shape':'Elipse','color':'Brown','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':5 ,'shape':'Square','color':'Green','quality':'Normal','size':1,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum', 'weight':5 ,'shape':'Elipse','color':'Gold','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
{'material':'Aluminum', 'weight':5 ,'shape':'Round','color':'Colorful','quality':'Old','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum', 'weight':6 ,'shape':'Square','color':'Brown','quality':'Normal','size':1,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum', 'weight':6 ,'shape':'Round','color':'Black','quality':'New','size':4,'temperature':1,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':6 ,'shape':'Non-regular','color':'Black','quality':'New','size':2,'temperature':3,'behavior':'Secure'},
{'material':'Aluminum', 'weight':4 ,'shape':'Non-regular','color':'Grey','quality':'Normal','size':1,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':3 ,'shape':'Elipse','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':1 ,'shape':'Round','color':'Brown','quality':'New','size':2,'temperature':3,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':1 ,'shape':'Elipse','color':'Black','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
{'material':'Aluminum', 'weight':1 ,'shape':'Square','color':'Gold','quality':'Normal','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Aluminum', 'weight':4 ,'shape':'Round','color':'Green','quality':'Normal','size':3,'temperature':1,'behavior':'Disarm'},
{'material':'Aluminum', 'weight':3 ,'shape':'Elipse','color':'Grey','quality':'Old','size':1,'temperature':2,'behavior':'Detonate'},

{'material':'Plastic','weight':1,'shape':'Non-regular','color':'Black','quality':'New','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Plastic','weight':1,'shape':'Square','color':'Brown','quality':'New','size':2,'temperature':1,'behavior':'Disarm'},
{'material':'Plastic','weight':2,'shape':'Non-regular','color':'Brown','quality':'New','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Gold','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Brown','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Grey','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic','weight':3,'shape':'Square','color':'Grey','quality':'Normal','size':3,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Black','quality':'Old','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Plastic','weight':3,'shape':'Square','color':'Grey','quality':'New','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Plastic','weight':4,'shape':'Round','color':'Grey','quality':'Old','size':1,'temperature':4,'behavior':'Secure'},
{'material':'Plastic','weight':4,'shape':'Round','color':'Grey','quality':'New','size':1,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':1 ,'shape':'Round','color':'Colorful','quality':'New','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Plastic', 'weight':1 ,'shape':'Elipse','color':'Black','quality':'Old','size':4,'temperature':2,'behavior':'Detonate'},
{'material':'Plastic', 'weight':2 ,'shape':'Non-regular','color':'Green','quality':'Normal','size':3,'temperature':1,'behavior':'Disarm'},
{'material':'Plastic', 'weight':2 ,'shape':'Elipse','color':'Black','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic', 'weight':2 ,'shape':'Round','color':'Brown','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':2 ,'shape':'Square','color':'Gold','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':3 ,'shape':'Round','color':'Brown','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':3 ,'shape':'Square','color':'Colorful','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic', 'weight':3 ,'shape':'Elipse','color':'Black','quality':'Normal','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Plastic', 'weight':3 ,'shape':'Round','color':'Green','quality':'Normal','size':1,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':4 ,'shape':'Elipse','color':'Grey','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
{'material':'Plastic', 'weight':4 ,'shape':'Square','color':'Brown','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':4 ,'shape':'Elipse','color':'Black','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':4 ,'shape':'Non-regular','color':'Black','quality':'Normal','size':1,'temperature':4,'behavior':'Secure'},
{'material':'Plastic', 'weight':4 ,'shape':'Square','color':'Green','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':4 ,'shape':'Round','color':'Brown','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
{'material':'Plastic', 'weight':5 ,'shape':'Elipse','color':'Gold','quality':'Normal','size':4,'temperature':3,'behavior':'Secure'},
{'material':'Plastic', 'weight':5 ,'shape':'Round','color':'Green','quality':'Old','size':1,'temperature':4,'behavior':'Secure'},
{'material':'Plastic', 'weight':5 ,'shape':'Non-regular','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':5 ,'shape':'Elipse','color':'Colorful','quality':'New','size':2,'temperature':1,'behavior':'Disarm'},
{'material':'Plastic', 'weight':5 ,'shape':'Round','color':'Gold','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':5 ,'shape':'Square','color':'Brown','quality':'New','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic', 'weight':5 ,'shape':'Round','color':'Black','quality':'Normal','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Plastic', 'weight':6 ,'shape':'Round','color':'Brown','quality':'Old','size':1,'temperature':2,'behavior':'Secure'},
{'material':'Plastic', 'weight':6 ,'shape':'Non-regular','color':'Colorful','quality':'New','size':3,'temperature':4,'behavior':'Secure'},
{'material':'Plastic', 'weight':6 ,'shape':'Elipse','color':'Black','quality':'Normal','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Plastic', 'weight':2 ,'shape':'Non-regular','color':'Colorful','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Plastic', 'weight':2 ,'shape':'Elipse','color':'Grey','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Plastic', 'weight':3 ,'shape':'Square','color':'Browm','quality':'Normal','size':4,'temperature':1,'behavior':'Disarm'},
{'material':'Plastic', 'weight':5 ,'shape':'Round','color':'Grey','quality':'Old','size':2,'temperature':4,'behavior':'Secure'},
{'material':'Plastic', 'weight':6 ,'shape':'Elipse','color':'Blakc','quality':'Normal','size':1,'temperature':4,'behavior':'Secure'},

{'material':'Wood','weight':1,'shape':'Non-regular','color':'Green','quality':'Normal','size':1,'temperature':2,'behavior':'Disarm'},
{'material':'Wood','weight':2,'shape':'Round','color':'Green','quality':'Normal','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Wood','weight':4,'shape':'Round','color':'Brown','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
{'material':'Wood', 'weight':1 ,'shape':'Round','color':'Brown','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
{'material':'Wood', 'weight':1 ,'shape':'Elipse','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Wood', 'weight':1 ,'shape':'Round','color':'Colorful','quality':'New','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Wood', 'weight':2 ,'shape':'Elipse','color':'Gold','quality':'Old','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Wood', 'weight':2 ,'shape':'Non-regular','color':'Grey','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Wood', 'weight':2 ,'shape':'Square','color':'Black','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Wood', 'weight':2 ,'shape':'Elipse','color':'Green','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
{'material':'Wood', 'weight':2 ,'shape':'Non-regular','color':'Brown','quality':'Normal','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':3 ,'shape':'Square','color':'Grey','quality':'New','size':4,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':3 ,'shape':'Round','color':'Gold','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
{'material':'Wood', 'weight':3 ,'shape':'Square','color':'Colorful','quality':'Normal','size':4,'temperature':2,'behavior':'Detonate'},
{'material':'Wood', 'weight':3 ,'shape':'Elipse','color':'Grey','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Wood', 'weight':3 ,'shape':'Round','color':'Black','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Wood', 'weight':3 ,'shape':'Elipse','color':'Green','quality':'Normal','size':4,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':4 ,'shape':'Square','color':'Brown','quality':'New','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Wood', 'weight':4 ,'shape':'Elipse','color':'Grey','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Wood', 'weight':4 ,'shape':'Non-regular','color':'Black','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Wood', 'weight':4 ,'shape':'Square','color':'Colorful','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
{'material':'Wood', 'weight':4 ,'shape':'Round','color':'Gold','quality':'New','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':4 ,'shape':'Elipse','color':'Grey','quality':'Normal','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':5 ,'shape':'Round','color':'Green','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
{'material':'Wood', 'weight':5 ,'shape':'Square','color':'Black','quality':'Normal','size':3,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':5 ,'shape':'Elipse','color':'Green','quality':'New','size':1,'temperature':2,'behavior':'Disarm'},
{'material':'Wood', 'weight':5 ,'shape':'Round','color':'Brown','quality':'Normal','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Wood', 'weight':6 ,'shape':'Elipse','color':'Green','quality':'New','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Wood', 'weight':6 ,'shape':'Elipse','color':'Geen','quality':'Old','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Wood', 'weight':6 ,'shape':'Non-regular','color':'Grey','quality':'Normal','size':2,'temperature':4,'behavior':'Secure'},
{'material':'Wood', 'weight':6 ,'shape':'Elipse','color':'Black','quality':'Old','size':3,'temperature':3,'behavior':'Secure'},
{'material':'Wood', 'weight':6 ,'shape':'Round','color':'Grey','quality':'Normal','size':2,'temperature':3,'behavior':'Secure'},

{'material':'Stone', 'weight':1 ,'shape':'Elipse','color':'Black','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
{'material':'Stone', 'weight':1 ,'shape':'Round','color':'Grey','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
{'material':'Stone', 'weight':1 ,'shape':'Non-regular','color':'Brown','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Stone', 'weight':2 ,'shape':'Round','color':'Gold','quality':'New','size':2,'temperature':1,'behavior':'Disarm'},
{'material':'Stone', 'weight':2 ,'shape':'Elipse','color':'Colorful','quality':'Old','size':4,'temperature':2,'behavior':'Detonate'},
{'material':'Stone', 'weight':2 ,'shape':'Round','color':'Black','quality':'Normal','size':2,'temperature':1,'behavior':'Disarm'},
{'material':'Stone', 'weight':3 ,'shape':'Elipse','color':'Green','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
{'material':'Stone', 'weight':3 ,'shape':'Non-regular','color':'Grey','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
{'material':'Stone', 'weight':3 ,'shape':'Elipse','color':'Brown','quality':'Normal','size':4,'temperature':2,'behavior':'Disarm'},
{'material':'Stone', 'weight':4 ,'shape':'Round','color':'Grey','quality':'Old','size':2,'temperature':2,'behavior':'Detonate'},
{'material':'Stone', 'weight':4 ,'shape':'Elipse','color':'Black','quality':'Old','size':1,'temperature':4,'behavior':'Secure'},
{'material':'Stone', 'weight':5 ,'shape':'Round','color':'Green','quality':'Nomral','size':3,'temperature':2,'behavior':'Disarm'},
{'material':'Stone', 'weight':5 ,'shape':'Elipse','color':'Grey','quality':'Old','size':2,'temperature':3,'behavior':'Secure'},
{'material':'Stone', 'weight':6 ,'shape':'Non-regular','color':'Black','quality':'Normal','size':4,'temperature':4,'behavior':'Secure'},
{'material':'Stone', 'weight':6 ,'shape':'Round','color':'Grey','quality':'New','size':1,'temperature':1,'behavior':'Disarm'},
{'material':'Stone', 'weight':6 ,'shape':'Elipse','color':'Colorful','quality':'Normal','size':3,'temperature':4,'behavior':'Secure'},
],

test_data : [
  	{'material':'Wood','weight':1,'shape':'Non-regular','color':'Green','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
    {'material':'Wood','weight':2,'shape':'Non-regular','color':'Brown','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
    {'material':'Wood','weight':2,'shape':'Round','color':'Green','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
    {'material':'Wood','weight':3,'shape':'Square','color':'Brown','quality':'Old','size':4,'temperature':2,'behavior':'Detonate'},
    {'material':'Wood', 'weight':4 ,'shape':'Round','color':'Gold','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
    {'material':'Wood','weight':4,'shape':'Non-regular','color':'Green','quality':'Normal','size':1,'temperature':2,'behavior':'Disarm'},
    {'material':'Wood','weight':5,'shape':'Square','color':'Brown','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
    {'material':'Wood', 'weight':4 ,'shape':'Round','color':'Colorful','quality':'New','size':4,'temperature':1,'behavior':'Disarm'},
    {'material':'Wood', 'weight':5 ,'shape':'Elipse','color':'Grey','quality':'Old','size':2,'temperature':3,'behavior':'Secure'},
    {'material':'Plastic','weight':1,'shape':'Round','color':'Gold','quality':'Normal','size':3,'temperature':2,'behavior':'Detonate'},
    {'material':'Plastic','weight':2,'shape':'Round','color':'Grey','quality':'Old','size':3,'temperature':2,'behavior':'Disarm'},
    {'material':'Plastic','weight':2,'shape':'Non-regular','color':'Black','quality':'Normal','size':2,'temperature':3,'behavior':'Detonate'},
    {'material':'Plastic', 'weight':4 ,'shape':'Non-regular','color':'Black','quality':'Normal','size':2,'temperature':4,'behavior':'Secure'},
    {'material':'Plastic', 'weight':2 ,'shape':'Square','color':'Gold','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
    {'material':'Plastic','weight':3,'shape':'Elipse','color':'Colorful','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
    {'material':'Plastic','weight':4,'shape':'Round','color':'Grey','quality':'New','size':3,'temperature':2,'behavior':'Disarm'},
    {'material':'Plastic','weight':4,'shape':'Square','color':'Grey','quality':'Normal','size':3,'temperature':3,'behavior':'Secure'},
    {'material':'Plastic','weight':5,'shape':'Square','color':'Brown','quality':'Normal','size':3,'temperature':4,'behavior':'Secure'},
    {'material':'Plastic', 'weight':6 ,'shape':'Elipse','color':'Green','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
    {'material':'Plastic', 'weight':3 ,'shape':'Non-regular','color':'Black','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
    {'material':'Metal','weight':1,'shape':'Round','color':'Grey','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
    {'material':'Metal','weight':2,'shape':'Square','color':'Grey','quality':'Old','size':2,'temperature':3,'behavior':'Detonate'},
    {'material':'Metal','weight':5,'shape':'Round','color':'Grey','quality':'Old','size':4,'temperature':3,'behavior':'Secure'},
    {'material':'Metal','weight':3,'shape':'Round','color':'Black','quality':'Old','size':3,'temperature':2,'behavior':'Disarm'},
    {'material':'Metal','weight':4,'shape':'Square','color':'Grey','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
    {'material':'Metal','weight':4,'shape':'Elipse','color':'Grey','quality':'Normal','size':1,'temperature':1,'behavior':'Disarm'},
    {'material':'Metal','weight':4,'shape':'Square','color':'Grey','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
    {'material':'Metal','weight':5,'shape':'Round','color':'Brown','quality':'Old','size':2,'temperature':3,'behavior':'Secure'},
    {'material':'Metal','weight':6,'shape':'Round','color':'Grey','quality':'Old','size':1,'temperature':4,'behavior':'Secure'},
    {'material':'Metal', 'weight':4 ,'shape':'Elipse','color':'Gold','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
    {'material':'Metal', 'weight':6 ,'shape':'Round','color':'Grey','quality':'New','size':4,'temperature':4,'behavior':'Secure'},
    {'material':'Metal', 'weight':3 ,'shape':'Square','color':'Colorful','quality':'Normal','size':3,'temperature':2,'behavior':'Disarm'},
    {'material':'Aluminum','weight':1,'shape':'Elipse','color':'Gold','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
    {'material':'Aluminum','weight':2,'shape':'Non-regular','color':'Colorful','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
    {'material':'Aluminum', 'weight':6 ,'shape':'Round','color':'Black','quality':'New','size':2,'temperature':2,'behavior':'Disarm'},
    {'material':'Aluminum','weight':3,'shape':'Round','color':'Grey','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
    {'material':'Aluminum','weight':4,'shape':'Square','color':'Brown','quality':'Old','size':4,'temperature':4,'behavior':'Secure'},
    {'material':'Aluminum','weight':5,'shape':'Round','color':'Browm','quality':'Normal','size':2,'temperature':2,'behavior':'Disarm'},
    {'material':'Aluminum', 'weight':5 ,'shape':'Elipse','color':'Gold','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
    {'material':'Aluminum', 'weight':4 ,'shape':'Elipse','color':'Brown','quality':'Old','size':3,'temperature':3,'behavior':'Detonate'},
    {'material':'Aluminum', 'weight':5 ,'shape':'Non-regular','color':'Green','quality':'Normal','size':2,'temperature':4,'behavior':'Secure'},
    {'material':'Aluminum', 'weight':1 ,'shape':'Square','color':'Gold','quality':'Old','size':1,'temperature':3,'behavior':'Detonate'},
    {'material':'Stone','weight':1,'shape':'Round','color':'Grey','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
    {'material':'Stone','weight':2,'shape':'Elipse','color':'Brown','quality':'Old','size':3,'temperature':2,'behavior':'Detonate'},
    {'material':'Stone','weight':4,'shape':'Elipse','color':'Black','quality':'Old','size':1,'temperature':3,'behavior':'Secure'},
    {'material':'Stone','weight':6,'shape':'Elipse','color':'Grey','quality':'Old','size':3,'temperature':4,'behavior':'Secure'},
    {'material':'Stone', 'weight':4 ,'shape':'Round','color':'Grey','quality':'Old','size':2,'temperature':2,'behavior':'Detonate'},
    {'material':'Stone', 'weight':5 ,'shape':'Round','color':'Green','quality':'Normal','size':3,'temperature':1,'behavior':'Disarm'},
    {'material':'Stone', 'weight':3 ,'shape':'Elipse','color':'Black','quality':'New','size':1,'temperature':3,'behavior':'Detonate'},
    {'material':'Stone', 'weight':6 ,'shape':'Round','color':'Grey','quality':'Normal','size':2,'temperature':4,'behavior':'Secure'},


  ],

  class_name : 'behavior',
  features : ['material','weight','shape','color','quality','size','temperature'],

   dt : new DecisionTree(this.training_data, this.class_name, this.features),

// mozna predykowac klase dla obiektu
//   var predicted_class = dt.predict({
//   	'material': "Wood",
//   	'weight': 2,
//     'shape': 'Round',
//     'color': 'Green',
//     'quality': 'New'
//   });
// test_data.forEach(function(element){
//     tmp=dt.predict({
//            'material':element.material,
//            'weight': element.weight,
//            'shape': element.shape,
//            'color': element.color,
//            'quality': element.quality
//        });
//     console.log(tmp + " rzeczywiste: " + element.behavior)
// });


//var accuracy = dt.evaluate(test_data);
//var treeModel = dt.toJSON();

// console.log(training_data.length);
// console.log(test_data.length);
//console.log((accuracy).toPrecision(2));
};