//This file contains example training data and samples


//some sample data we'll be using
//http://www.cise.ufl.edu/~ddd/cap6635/Fall-97/Short-papers/2.htm
// var examples = [
// {day:'D1',outlook:'Sunny', temp:'Hot', humidity:'High', wind: 'Weak',play:'No'},
// {day:'D2',outlook:'Sunny', temp:'Hot', humidity:'High', wind: 'Strong',play:'No'},
// {day:'D3',outlook:'Overcast', temp:'Hot', humidity:'High', wind: 'Weak',play:'Yes'},
// {day:'D4',outlook:'Rain', temp:'Mild', humidity:'High', wind: 'Weak',play:'Yes'},
// {day:'D5',outlook:'Rain', temp:'Cool', humidity:'Normal', wind: 'Weak',play:'Yes'},
// {day:'D6',outlook:'Rain', temp:'Cool', humidity:'Normal', wind: 'Strong',play:'No'},
// {day:'D7',outlook:'Overcast', temp:'Cool', humidity:'Normal', wind: 'Strong',play:'Yes'},
// {day:'D8',outlook:'Sunny', temp:'Mild', humidity:'High', wind: 'Weak',play:'No'},
// {day:'D9',outlook:'Sunny', temp:'Cool', humidity:'Normal', wind: 'Weak',play:'Yes'},
// {day:'D10',outlook:'Rain', temp:'Mild', humidity:'Normal', wind: 'Weak',play:'Yes'},
// {day:'D11',outlook:'Sunny', temp:'Mild', humidity:'Normal', wind: 'Strong',play:'Yes'},
// {day:'D12',outlook:'Overcast', temp:'Mild', humidity:'High', wind: 'Strong',play:'Yes'},
// {day:'D13',outlook:'Overcast', temp:'Hot', humidity:'Normal', wind: 'Weak',play:'Yes'},
// {day:'D14',outlook:'Rain', temp:'Mild', humidity:'High', wind: 'Strong',play:'No'}
// ];

// examples = _(examples);
// var features = ['outlook', 'temp', 'humidity', 'wind'];
// var samples = [{outlook:'Overcast', temp:'Mild', humidity:'High', wind: 'Strong',play: 'Yes'},
// 	       {outlook:'Rain', temp:'Mild', humidity:'High', wind: 'Strong', play: 'No'},
// 	       {outlook:'Sunny', temp:'Cool', humidity:'Normal', wind: 'Weak', play: 'Yes'}]

var examples =
[{'material':'Stone','weight':1,'shape':'Round','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':1,'shape':'Round','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':2,'shape':'Round','color':'Grey','quality':'Normal','isBomb':'No'},
{'material':'Stone','weight':2,'shape':'Elipse','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':3,'shape':'Round','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':3,'shape':'Round','color':'Black','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':3,'shape':'Round','color':'Black','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':3,'shape':'Round','color':'Black','quality':'Normal','isBomb':'No'},
{'material':'Stone','weight':3,'shape':'Elipse','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':4,'shape':'Round','color':'Brown','quality':'New','isBomb':'No'},
{'material':'Stone','weight':4,'shape':'Elipse','color':'Grey','quality':'Normal','isBomb':'No'},
{'material':'Stone','weight':4,'shape':'Non-regular','color':'Grey','quality':'Normal','isBomb':'No'},
{'material':'Stone','weight':4,'shape':'Non-regular','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':5,'shape':'Elipse','color':'Black','quality':'New','isBomb':'No'},
{'material':'Stone','weight':5,'shape':'Elipse','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':5,'shape':'Non-regular','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':6,'shape':'Elipse','color':'Black','quality':'New','isBomb':'No'},
{'material':'Stone','weight':6,'shape':'Elipse','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Metal','weight':1,'shape':'Round','color':'Gold','quality':'Old','isBomb':'No'},
{'material':'Metal','weight':1,'shape':'Square','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Metal','weight':1,'shape':'Non-regular','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Metal','weight':2,'shape':'Square','color':'Colorful','quality':'New','isBomb':'No'},
{'material':'Metal','weight':2,'shape':'Square','color':'Brown','quality':'Normal','isBomb':'No'},
{'material':'Metal','weight':2,'shape':'Non-regular','color':'Black','quality':'Normal','isBomb':'No'},
{'material':'Metal','weight':3,'shape':'Round','color':'Grey','quality':'Old','isBomb':'Yes'},
{'material':'Metal','weight':3,'shape':'Round','color':'Brown','quality':'New','isBomb':'Yes'},
{'material':'Metal','weight':3,'shape':'Square','color':'Colorful','quality':'Normal','isBomb':'No'},
{'material':'Metal','weight':3,'shape':'Square','color':'Black','quality':'Old','isBomb':'Yes'},
{'material':'Metal','weight':4,'shape':'Round','color':'Black','quality':'New','isBomb':'Yes'},
{'material':'Metal','weight':4,'shape':'Round','color':'Brown','quality':'Old','isBomb':'Yes'},
{'material':'Metal','weight':4,'shape':'Round','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Metal','weight':4,'shape':'Square','color':'Grey','quality':'Normal','isBomb':'Yes'},
{'material':'Metal','weight':4,'shape':'Square','color':'Black','quality':'Normal','isBomb':'Yes'},
{'material':'Metal','weight':5,'shape':'Elipse','color':'Green','quality':'Normal','isBomb':'Yes'},
{'material':'Metal','weight':5,'shape':'Round','color':'Grey','quality':'Old','isBomb':'Yes'},
{'material':'Metal','weight':5,'shape':'Round','color':'Black','quality':'Normal','isBomb':'Yes'},
{'material':'Metal','weight':6,'shape':'Non-regular','color':'Colorful','quality':'New','isBomb':'Yes'},
{'material':'Metal','weight':6,'shape':'Round','color':'Grey','quality':'Old','isBomb':'Yes'},
{'material':'Metal','weight':6,'shape':'Round','color':'Grey','quality':'Old','isBomb':'Yes'},
{'material':'Metal','weight':6,'shape':'Elipse','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Aluminum','weight':1,'shape':'Non-regular','color':'Grey','quality':'New','isBomb':'No'},
{'material':'Aluminum','weight':1,'shape':'Round','color':'Grey','quality':'New','isBomb':'No'},
{'material':'Aluminum','weight':1,'shape':'Square','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Aluminum','weight':2,'shape':'Elipse','color':'Grey','quality':'Normal','isBomb':'Yes'},
{'material':'Aluminum','weight':2,'shape':'Elipse','color':'Grey','quality':'New','isBomb':'Yes'},
{'material':'Aluminum','weight':2,'shape':'Elipse','color':'Colorful','quality':'New','isBomb':'No'},
{'material':'Aluminum','weight':2,'shape':'Non-regular','color':'Colorful','quality':'New','isBomb':'No'},
{'material':'Aluminum','weight':2,'shape':'Round','color':'Colorful','quality':'Old','isBomb':'Yes'},
{'material':'Aluminum','weight':2,'shape':'Round','color':'Green','quality':'New','isBomb':'Yes'},
{'material':'Aluminum','weight':2,'shape':'Round','color':'Green','quality':'Old','isBomb':'No'},
{'material':'Aluminum','weight':3,'shape':'Elipse','color':'Gold','quality':'Normal','isBomb':'No'},
{'material':'Aluminum','weight':3,'shape':'Elipse','color':'Gold','quality':'Normal','isBomb':'No'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Green','quality':'Old','isBomb':'Yes'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Grey','quality':'New','isBomb':'Yes'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Black','quality':'Old','isBomb':'Yes'},
{'material':'Aluminum','weight':3,'shape':'Square','color':'Grey','quality':'Normal','isBomb':'No'},
{'material':'Aluminum','weight':4,'shape':'Non-regular','color':'Grey','quality':'Normal','isBomb':'No'},
{'material':'Aluminum','weight':4,'shape':'Round','color':'Grey','quality':'Normal','isBomb':'Yes'},
{'material':'Aluminum','weight':4,'shape':'Round','color':'Brown','quality':'Old','isBomb':'Yes'},
{'material':'Aluminum','weight':4,'shape':'Square','color':'Black','quality':'Normal','isBomb':'No'},
{'material':'Aluminum','weight':5,'shape':'Round','color':'Grey','quality':'Normal','isBomb':'Yes'},
{'material':'Plastic','weight':1,'shape':'Non-regular','color':'Colorful','quality':'Normal','isBomb':'No'},
{'material':'Plastic','weight':1,'shape':'Non-regular','color':'Colorful','quality':'Old','isBomb':'No'},
{'material':'Plastic','weight':1,'shape':'Non-regular','color':'Colorful','quality':'New','isBomb':'No'},
{'material':'Plastic','weight':1,'shape':'Non-regular','color':'Brown','quality':'New','isBomb':'No'},
{'material':'Plastic','weight':1,'shape':'Non-regular','color':'Black','quality':'New','isBomb':'Yes'},
{'material':'Plastic','weight':1,'shape':'Square','color':'Brown','quality':'New','isBomb':'Yes'},
{'material':'Plastic','weight':1,'shape':'Round','color':'Grey','quality':'New','isBomb':'No'},
{'material':'Plastic','weight':2,'shape':'Round','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Plastic','weight':2,'shape':'Non-regular','color':'Brown','quality':'New','isBomb':'Yes'},
{'material':'Plastic','weight':2,'shape':'Round','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Plastic','weight':2,'shape':'Elipse','color':'Colorful','quality':'New','isBomb':'No'},
{'material':'Plastic','weight':3,'shape':'Square','color':'Gold','quality':'Normal','isBomb':'No'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Gold','quality':'Old','isBomb':'Yes'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Brown','quality':'Old','isBomb':'Yes'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Grey','quality':'New','isBomb':'Yes'},
{'material':'Plastic','weight':3,'shape':'Round','color':'Black','quality':'Old','isBomb':'Yes'},
{'material':'Plastic','weight':3,'shape':'Non-regular','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Plastic','weight':3,'shape':'Square','color':'Grey','quality':'New','isBomb':'Yes'},
{'material':'Plastic','weight':4,'shape':'Round','color':'Grey','quality':'New','isBomb':'Yes'},
{'material':'Plastic','weight':5,'shape':'Square','color':'Gold','quality':'Normal','isBomb':'No'},
{'material':'Wood','weight':1,'shape':'Non-regular','color':'Green','quality':'Normal','isBomb':'Yes'},
{'material':'Wood','weight':1,'shape':'Non-regular','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':1,'shape':'Round','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':2,'shape':'Round','color':'Green','quality':'Normal','isBomb':'Yes'},
{'material':'Wood','weight':2,'shape':'Round','color':'Green','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':2,'shape':'Square','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':3,'shape':'Elipse','color':'Grey','quality':'New','isBomb':'No'},
{'material':'Wood','weight':3,'shape':'Non-regular','color':'Green','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':4,'shape':'Round','color':'Brown','quality':'Old','isBomb':'Yes'},
{'material':'Wood','weight':5,'shape':'Non-regular','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':5,'shape':'Square','color':'Green','quality':'Old','isBomb':'No'},
{'material':'Wood','weight':6,'shape':'Square','color':'Green','quality':'Old','isBomb':'No'}];

examples = _(examples);
var features = ['material','weight','shape','color','quality'];

var samples = [
{'material':'Wood','weight':4,'shape':'Non-regular','color':'Brown','quality':'Old','isBomb':'No'},
{'material':'Plastic','weight':2,'shape':'Square','color':'Grey','quality':'Normal','isBomb':'No'},
{'material':'Aluminum','weight':3,'shape':'Round','color':'Grey','quality':'Old','isBomb':'Yes'},
{'material':'Aluminum','weight':1,'shape':'Elipse','color':'Gold','quality':'Old','isBomb':'No'},
{'material':'Stone','weight':6,'shape':'Round','color':'Grey','quality':'Old','isBomb':'No'},
{'material':'Metal','weight':4,'shape':'Round','color':'Black','quality':'Old','isBomb':'Yes'},
];